/Binaries/
/Build/
/DerivedDataCache/
/Intermediate/
/Saved/
/Script/
enc_temp_folder/
**/Content/StarterContent/
*.log
*.tmp
*.bak
.idea/
.vscode/
.vs/
.vsconfig
*.VC.db
*.opensdf
*.opendb
*.sdf
*.suo
*.sln
*.code-workspace
.idea/
*.iml
*.xcodeproj
*.xcworkspace
DerivedDataCache/
LocalDerivedDataCache/
Saved/CrashReports/
*.pdb
!*.uproject
!Source/
/.idea
