# Fichiers générés par Unreal Engine
/Binaries/
/Build/
/DerivedDataCache/
/Intermediate/
/Saved/
/Script/
enc_temp_folder/
/Content/StarterContent/

# Fichiers de logs et temporaires
*.log
*.tmp
*.bak

# Fichiers liés aux IDE et outils
.idea/
.vscode/
.vs/
.vsconfig
*.VC.db
*.opensdf
*.opendb
*.sdf
*.suo
*.sln
*.code-workspace

# Fichiers MacOS ou XCode
*.xcodeproj
*.xcworkspace

# Données locales supplémentaires
DerivedDataCache/
LocalDerivedDataCache/

# Rapports de crash
Saved/CrashReports/

# Fichiers de débogage
*.pdb

# Important : exclure les fichiers inutiles mais préserver ceux nécessaires
!*.uproject
!Source/
!Content/