;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="Attribute.ShieldMod",NewTagName="Attribute.Shield")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attribute.Health",DevComment="")
+GameplayTagList=(Tag="Attribute.Shield",DevComment="")
+GameplayTagList=(Tag="Event.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Spell",DevComment="")
+GameplayTagList=(Tag="Event.Spell.Ice",DevComment="")
+GameplayTagList=(Tag="Spell.Fire",DevComment="")
+GameplayTagList=(Tag="Spell.Poison",DevComment="")
+GameplayTagList=(Tag="Spell.Shield",DevComment="")
+GameplayTagList=(Tag="StateTree.TargetEnemy",DevComment="")
+GameplayTagList=(Tag="StateTree.UnTargetEnemy",DevComment="")

